# Generated by Django 5.2.1 on 2025-05-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0003_remove_tarea_archivo_adjunto_tarea_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='HistorialTarea',
        ),
    ]
