# Generated by Django 5.2.1 on 2025-06-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0005_alter_movimiento_estado_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='plano',
            field=models.ImageField(blank=True, null=True, upload_to='planos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='perfil',
            field=models.CharField(choices=[('operario', 'Operario'), ('calidad', 'calidad'), ('ppc', 'ppc'), ('admin', 'Administrador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='tareas_app.empleado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas_app.empleado'),
        ),
    ]
