# Generated by Django 5.2.1 on 2025-07-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0008_tarea_cantidad_tarea_enominacion_tarea_estructura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='enominacion',
            new_name='denominacion',
        ),
    ]
