# Generated by Django 5.2.1 on 2025-07-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0009_rename_enominacion_tarea_denominacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='perfil',
            field=models.CharField(choices=[('ingenieria', 'Ingeniería'), ('calidad', 'Calidad'), ('despacho', 'Despacho'), ('rrhh', 'RRHH'), ('produccion', 'Producción'), ('ppc', 'PPC'), ('administrador', 'Administrador'), ('armador', 'Armador'), ('soldador', 'Soldador'), ('pintor', 'Pintor'), ('corte', 'Corte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
