# Generated by Django 5.2.1 on 2025-07-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0010_empleado_nombre_alter_empleado_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
    ]
