# Generated by Django 5.2.1 on 2025-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0013_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('en_revision', 'En revision'), ('lista_para_pintar', 'Lista para pintar'), ('lista_para_despachar', 'Lista para despachar'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('en_revision', 'En revision'), ('lista_para_pintar', 'Lista para pintar'), ('lista_para_despachar', 'Lista para despachar'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
