# Generated by Django 5.2.4 on 2025-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tareas_app", "0013_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("armado", "Armado"),
                    ("soldado", "Soldado"),
                    ("pintura", "Pintura"),
                    ("despacho", "Despacho"),
                    ("galvanizado", "Galvanizado"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En proceso"),
                    ("en_revision", "En revision"),
                    ("lista_para_pintar", "Lista para pintar"),
                    ("galvanizado", "Galvanizado"),
                    ("lista_para_despachar", "Lista para despachar"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En proceso"),
                    ("en_revision", "En revision"),
                    ("lista_para_pintar", "Lista para pintar"),
                    ("galvanizado", "Galvanizado"),
                    ("lista_para_despachar", "Lista para despachar"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
