# Generated by Django 5.2.1 on 2025-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0014_alter_movimiento_estado_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='sector',
            field=models.CharField(blank=True, choices=[('armado', 'Armado'), ('soldado', 'Soldado'), ('pintado', 'Pintado'), ('despachar', 'Despachar'), ('galvanizado', 'Galvanizado'), ('control', 'Control')], max_length=20, null=True),
        ),
    ]
