# Generated by Django 5.2.1 on 2025-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0016_alter_tarea_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='sector',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('armado', 'Armado'), ('control_1', 'Control 1'), ('soldado', 'Soldado'), ('control_2', 'Control 2'), ('pintado', 'Pintado'), ('despachar', 'Despachar'), ('galvanizado', 'Galvanizado')], max_length=20, null=True),
        ),
    ]
