# Generated by Django 5.2.1 on 2025-07-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0017_alter_tarea_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='sector',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('armado', 'Armado'), ('control_1', 'Control 1'), ('soldado', 'Soldado'), ('control_2', 'Control 2'), ('pintado', 'Pintado'), ('despachar', 'Despachar'), ('galvanizado', 'Galvanizado')], default='pendiente', max_length=30),
        ),
    ]
