# Generated by Django 5.2.1 on 2025-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0018_ordendetrabajo_finalizada_alter_tarea_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='operarios',
            field=models.ManyToManyField(blank=True, related_name='tareas_operadas', to='tareas_app.empleado'),
        ),
    ]
