# Generated by Django 5.2.1 on 2025-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0020_movimiento_hecho_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
