# Generated by Django 5.2.1 on 2025-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0021_movimiento_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
