# Generated by Django 5.2.1 on 2025-07-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0022_movimiento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteexterno',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='agenteexterno',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='agenteexterno',
            name='nombre',
        ),
    ]
