# Generated by Django 5.2.1 on 2025-07-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas_app', '0023_remove_agenteexterno_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
